apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: go-web
spec:
  selector:
    matchLabels:
      app: go-web
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: go-web
    spec:
      containers:
      - name: go-web
        image: jerome521/go-web-hello-world:v0.1
        ports:
        - containerPort: 8081
          protocol: TCP
