apiVersion: v1
kind: Service
metadata:
  name: go-web
  labels:
    app: go-web
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 31080
    protocol: TCP
  selector:
    app: go-web
